//
//  3dModelData.swift
//  AssistantReality
//
//  Created by Vicky Irwanto on 02/06/23.
//

import SwiftUI
import SceneKit


struct HairModel: Identifiable, Hashable{
    var id: UUID = .init()
    var faceType: String
    var name: String
    var icon: SCNScene?
    var iconName: String
    var isFavorite: Bool = false
    var description: String
}


var HairModels : [HairModel] = [
//    Oval
    .init(faceType:"oval", name: "Buzz Cut", icon: .init(named: "OvalBuzzCut.usdz"), iconName: "OvalBuzzCut", isFavorite: true, description: "Buzz Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut it evenly short using the clippers on the top, sides and back. On the front hairline is made more assertive. And for the sides and back you can ask for a Fade/Taper cut."),
    .init(faceType:"oval", name: "Side Part", icon: .init(named: "OvalSidePart.usdz"), iconName: "OvalSidePart", isFavorite: true, description: "Side Part is suitable for customers who want to have a classic haircut and not look old, and is also suitable for attending formal events. This haircut is suitable for customers who have straight or wavy hair types. You can tell the barber not to cut the top of your hair too short so you can comb it to the right or left side of your head, and you can ask the sides and back of your hair to be cut Natural/Fade/Taper."),
    .init(faceType:"oval", name: "Pompadour", icon: .init(named: "OvalPompadour.usdz"), iconName: "OvalPompadour", isFavorite: true, description: "Pompadour is haircut that is suitable for young customers with a contemporary style. This style also looks very elegant, so it is suitable for formal and non-formal events. This cut is only suitable for wavy and straight hair types. You can tell the barber not to cut the front bangs too short, so you can style your brush left and right as you wish. You can also ask the barber to trim the sides and back in a taper, fade, or natural style, according to your preference. However, this style may not suit someone with a wide forehead shape, as the pompadour usually accentuates the top of the head. With the pompadour, you will get a trendy and elegant look. This style gives off a classy feel and can elevate your overall look. Make sure to choose a cut that suits your hair texture and takes your face shape into account for optimal results."),
    .init(faceType:"oval", name: "Short Crew Cut", icon: .init(named: "OvalShortCrewCut.usdz"), iconName: "OvalShortCrewCut", isFavorite: true, description: "The Short Crew Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut the top into 2 cm to 4 cm, and on the sides and back you can ask for a Fade/Taper cut."),
    .init(faceType:"oval", name: "Spiky", icon: .init(named: "OvalSpiky.usdz"), iconName: "OvalSpiky", isFavorite: true, description: "Spiky is suitable for customers who want bold and edgy looks. This haircut is suitable for customers with all types of hair types. You can tell the barber to cut the top of your hair with a clipper according to the length you want, then ask for texture. Then for some types of hair, hair products are needed to maintain the shape of the haircut so that it still looks like a 'spike'. And for the side you can ask for a Fade/Taper/Natural cut."),
//    .init(faceType:"oval", name: "Taper Slick Back", icon: .init(named: "OvalTaperSlickback.usdz"), iconName: "OvalTaperSlickback", isFavorite: true, description: "Taper Slick Back is suitable for customers who want to look elegant and neat. This haircut is suitable for customers who have straight or wavy hair types. This haircut usually has a slightly longer top hair length. You can tell the barber to adjust the top haircut so that it can be combed towards the back of your head, but one must consider the width of the forehead while choosing this haircut. And also for this haircut you need hair products to hold your top hair so it stays pointing backwards. And for the sides and back of your hair, you can ask for a taper cut."),
    
    
//    Round
    .init(faceType:"round", name: "Buzz Cut", icon: .init(named: "RoundBuzzCut.usdz"), iconName: "RoundBuzzCut", isFavorite: true, description: "Buzz Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut it evenly short using the clippers on the top, sides and back. On the front hairline is made more assertive. And for the sides and back you can ask for a Fade/Taper cut."),
    .init(faceType:"round", name: "Side Part", icon: .init(named: "RoundSidePart.usdz"), iconName: "RoundSidePart", isFavorite: true, description: "Side Part is suitable for customers who want to have a classic haircut and not look old, and is also suitable for attending formal events. This haircut is suitable for customers who have straight or wavy hair types. You can tell the barber not to cut the top of your hair too short so you can comb it to the right or left side of your head, and you can ask the sides and back of your hair to be cut Natural/Fade/Taper."),
//    .init(faceType:"round", name: "Pompadour", icon: .init(named: "RoundPompadour.usdz"), iconName: "RoundPompadour", isFavorite: true, description: "Pompadour is haircut that is suitable for young customers with a contemporary style. This style also looks very elegant, so it is suitable for formal and non-formal events. This cut is only suitable for wavy and straight hair types. You can tell the barber not to cut the front bangs too short, so you can style your brush left and right as you wish. You can also ask the barber to trim the sides and back in a taper, fade, or natural style, according to your preference. However, this style may not suit someone with a wide forehead shape, as the pompadour usually accentuates the top of the head. With the pompadour, you will get a trendy and elegant look. This style gives off a classy feel and can elevate your overall look. Make sure to choose a cut that suits your hair texture and takes your face shape into account for optimal results."),
    .init(faceType:"round", name: "Short Crew Cut", icon: .init(named: "RoundShortCrewCut.usdz"), iconName: "RoundShortCrewCut", isFavorite: true, description: "The Short Crew Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut the top into 2 cm to 4 cm, and on the sides and back you can ask for a Fade/Taper cut."),
    .init(faceType:"round", name: "Spiky", icon: .init(named: "RoundSpiky.usdz"), iconName: "RoundSpiky", isFavorite: true, description: "Spiky is suitable for customers who want bold and edgy looks. This haircut is suitable for customers with all types of hair types. You can tell the barber to cut the top of your hair with a clipper according to the length you want, then ask for texture. Then for some types of hair, hair products are needed to maintain the shape of the haircut so that it still looks like a 'spike'. And for the side you can ask for a Fade/Taper/Natural cut."),
    .init(faceType:"round", name: "Taper Slick Back", icon: .init(named: "RoundTaperSlickback.usdz"), iconName: "RoundTaperSlickback", isFavorite: true, description: "Taper Slick Back is suitable for customers who want to look elegant and neat. This haircut is suitable for customers who have straight or wavy hair types. This haircut usually has a slightly longer top hair length. You can tell the barber to adjust the top haircut so that it can be combed towards the back of your head, but one must consider the width of the forehead while choosing this haircut. And also for this haircut you need hair products to hold your top hair so it stays pointing backwards. And for the sides and back of your hair, you can ask for a taper cut."),
    
    //Rectangle
        .init(faceType:"rectangle", name: "BuzzCut", icon: .init(named: "RectangleBuzzCut.usdz"), iconName: "RectangleBuzzCut", isFavorite: true, description: "Buzz Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut it evenly short using the clippers on the top, sides and back. On the front hairline is made more assertive. And for the sides and back you can ask for a Fade/Taper cut."),
        .init(faceType:"rectangle", name: "Pompadour", icon: .init(named: "RectanglePompadour.usdz"), iconName: "RectanglePompadour", isFavorite: true, description: "Pompadour is haircut that is suitable for young customers with a contemporary style. This style also looks very elegant, so it is suitable for formal and non-formal events. This cut is only suitable for wavy and straight hair types. You can tell the barber not to cut the front bangs too short, so you can style your brush left and right as you wish. You can also ask the barber to trim the sides and back in a taper, fade, or natural style, according to your preference. However, this style may not suit someone with a wide forehead shape, as the pompadour usually accentuates the top of the head. With the pompadour, you will get a trendy and elegant look. This style gives off a classy feel and can elevate your overall look. Make sure to choose a cut that suits your hair texture and takes your face shape into account for optimal results."),
        .init(faceType:"rectangle", name: "ShortCrewCut", icon: .init(named: "RectangleShortCrewCut.usdz"), iconName: "RectangleShortCrewCut", isFavorite: true, description: "The Short Crew Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut the top into 2 cm to 4 cm, and on the sides and back you can ask for a Fade/Taper cut"),
        .init(faceType:"rectangle", name: "SidePart", icon: .init(named: "RectangleSidePart.usdz"), iconName: "RectangleSidePart", isFavorite: true, description: "Side Part is suitable for customers who want to have a classic haircut and not look old, and is also suitable for attending formal events. This haircut is suitable for customers who have straight or wavy hair types. You can tell the barber not to cut the top of your hair too short so you can comb it to the right or left side of your head, and you can ask the sides and back of your hair to be cut Natural/Fade/Taper. \n \nDisclaimer!! to get a haircut according to what you want, try to discuss the haircut you want in as much detail as possible with the barber"),
        .init(faceType:"rectangle", name: "Spiky", icon: .init(named: "RectangleSpiky.usdz"), iconName: "RectangleSpiky", isFavorite: true, description: "Spiky is suitable for customers who want bold and edgy looks. This haircut is suitable for customers with all types of hair types. You can tell the barber to cut the top of your hair with a clipper according to the length you want, then ask for texture. Then for some types of hair, hair products are needed to maintain the shape of the haircut so that it still looks like a 'spike'. And for the side you can ask for a Fade/Taper/Natural cut."),
        .init(faceType:"rectangle", name: "TaperSlickBack", icon: .init(named: "RectangleTaperSlickback.usdz"), iconName: "RectangleTaperSlickback", isFavorite: true, description: "Taper Slick Back is suitable for customers who want to look elegant and neat. This haircut is suitable for customers who have straight or wavy hair types. This haircut usually has a slightly longer top hair length. You can tell the barber to adjust the top haircut so that it can be combed towards the back of your head, but one must consider the width of the forehead while choosing this haircut. And also for this haircut you need hair products to hold your top hair so it stays pointing backwards. And for the sides and back of your hair, you can ask for a taper cut."),
        
        //Diamond
        .init(faceType:"diamond", name: "BuzzCut", icon: .init(named: "DiamondBuzzCut.usdz"), iconName: "DiamondBuzzCut", isFavorite: true, description: "Buzz Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut it evenly short using the clippers on the top, sides and back. On the front hairline is made more assertive. And for the sides and back you can ask for a Fade/Taper cut."),
        .init(faceType:"diamond", name: "Pompadour", icon: .init(named: "DiamondPompadour.usdz"), iconName: "DiamondPompadour", isFavorite: true, description: "Pompadour is haircut that is suitable for young customers with a contemporary style. This style also looks very elegant, so it is suitable for formal and non-formal events. This cut is only suitable for wavy and straight hair types. You can tell the barber not to cut the front bangs too short, so you can style your brush left and right as you wish. You can also ask the barber to trim the sides and back in a taper, fade, or natural style, according to your preference. However, this style may not suit someone with a wide forehead shape, as the pompadour usually accentuates the top of the head. With the pompadour, you will get a trendy and elegant look. This style gives off a classy feel and can elevate your overall look. Make sure to choose a cut that suits your hair texture and takes your face shape into account for optimal results."),
        .init(faceType:"diamond", name: "ShortCrewCFut", icon: .init(named: "DiamondShortCrewCut.usdz"), iconName: "DiamondShortCrewCut", isFavorite: true, description: "The Short Crew Cut is suitable for customers who want to look elegant, neat, and like to exercise. This haircut is suitable for all hair types. This haircut doesn't require too long top hair. You can tell the barber to cut the top into 2 cm to 4 cm, and on the sides and back you can ask for a Fade/Taper cut"),
        .init(faceType:"diamond", name: "SidePart", icon: .init(named: "DiamondSidePart.usdz"), iconName: "DiamondSidePart", isFavorite: true, description: "Side Part is suitable for customers who want to have a classic haircut and not look old, and is also suitable for attending formal events. This haircut is suitable for customers who have straight or wavy hair types. You can tell the barber not to cut the top of your hair too short so you can comb it to the right or left side of your head, and you can ask the sides and back of your hair to be cut Natural/Fade/Taper. \n \nDisclaimer!! to get a haircut according to what you want, try to discuss the haircut you want in as much detail as possible with the barber"),
        .init(faceType:"diamond", name: "Spiky", icon: .init(named: "DiamondSpiky.usdz"), iconName: "DiamondSpiky", isFavorite: true, description: "Spiky is suitable for customers who want bold and edgy looks. This haircut is suitable for customers with all types of hair types. You can tell the barber to cut the top of your hair with a clipper according to the length you want, then ask for texture. Then for some types of hair, hair products are needed to maintain the shape of the haircut so that it still looks like a 'spike'. And for the side you can ask for a Fade/Taper/Natural cut."),
        .init(faceType:"diamond", name: "TaperSlickBack", icon: .init(named: "DiamondTaperSlickBack.usdz"), iconName: "DiamondTaperSlickBack", isFavorite: true, description: "Taper Slick Back is suitable for customers who want to look elegant and neat. This haircut is suitable for customers who have straight or wavy hair types. This haircut usually has a slightly longer top hair length. You can tell the barber to adjust the top haircut so that it can be combed towards the back of your head, but one must consider the width of the forehead while choosing this haircut. And also for this haircut you need hair products to hold your top hair so it stays pointing backwards. And for the sides and back of your hair, you can ask for a taper cut."),
    
    
]
